name: skullgive
version: '${project.version}'
main: com.github.sirokuri_.skullgive.skullgive
api-version: 1.12
authors: [46kuri_]
description: LGW pligin

commands:
  skullgive:
    description: ヘッド入手コマンド
    permission: Skullgive.permission.skullgive

permissions:
  Skullgive.permission.skullgive:
    default: op
